In [5]:
a= [1,4,256]
type(a)

list

In [6]:
import numpy as np

In [7]:
r=np.random.randint(0,255,(10,10))
r

array([[159, 200, 143,  85, 156, 206, 220, 220,  69,  42],
       [249,  54,  27, 249,  21,  62, 136,  38, 227, 113],
       [179,   9, 221, 184,  86,  88, 185, 166, 100, 156],
       [ 80, 146,  16, 127,  21,   4,  15, 237, 239,  28],
       [160, 199,  62, 170,  17, 215,  85, 162, 110, 139],
       [131, 134, 143,  86, 167,  58, 212, 248, 233, 174],
       [ 47,   5,  86, 206, 219,  92,   2, 176,  69, 113],
       [116,  55, 210, 188, 254, 140,   6, 156, 194, 209],
       [205,  94,   2, 186, 156, 250,  24, 250, 109, 179],
       [ 46,  75, 154, 135,  35,  37, 147,   6,  78, 152]])

In [8]:
r.dtype

dtype('int32')

In [9]:
r=np.random.randint(0,255,(10,10),dtype=np.uint8)
r

array([[169, 198, 150, 238,  92,  15,  56,  46, 200, 130],
       [129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,  27,  65, 103, 199, 119, 190],
       [163, 244, 151,  86,  92,  13,   4, 232, 234,  80],
       [ 74, 112, 116, 254, 233, 170, 144, 254, 174,  78],
       [132,   9, 224, 237, 186,  97,  43, 168, 155,  95],
       [194, 108, 205,  75,  57, 206, 190, 243,   8,  43],
       [ 52, 148,  22, 241,   7, 178,  16,  70, 148, 185],
       [140, 102, 185,  63,  25, 112,  33,  31, 166, 105],
       [ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0]], dtype=uint8)

In [10]:
r2=r.astype(np.uint16)
r2

array([[169, 198, 150, 238,  92,  15,  56,  46, 200, 130],
       [129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,  27,  65, 103, 199, 119, 190],
       [163, 244, 151,  86,  92,  13,   4, 232, 234,  80],
       [ 74, 112, 116, 254, 233, 170, 144, 254, 174,  78],
       [132,   9, 224, 237, 186,  97,  43, 168, 155,  95],
       [194, 108, 205,  75,  57, 206, 190, 243,   8,  43],
       [ 52, 148,  22, 241,   7, 178,  16,  70, 148, 185],
       [140, 102, 185,  63,  25, 112,  33,  31, 166, 105],
       [ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0]], dtype=uint16)

In [12]:
rgb=np.random.randint(0,255,(10,10,3))
rgb

array([[[119,  79, 235],
        [134, 185,  52],
        [ 19, 222, 151],
        [ 38,  70,  85],
        [156, 117,  70],
        [126, 172, 163],
        [ 23, 225, 232],
        [188, 194,  41],
        [251, 137,  19],
        [232,  52, 222]],

       [[160,  22,   9],
        [114,  94, 118],
        [ 56, 234,  18],
        [128, 237,  10],
        [162,  77,  68],
        [186, 116,  62],
        [182, 146, 240],
        [ 96,  85,  21],
        [ 29, 159, 252],
        [167, 102,  97]],

       [[ 27, 234, 175],
        [ 90, 111, 130],
        [218,  84, 237],
        [116, 184, 232],
        [179, 148,  90],
        [110, 247,  77],
        [251, 213,  74],
        [ 62, 132, 147],
        [143, 107, 227],
        [ 44, 243, 114]],

       [[245, 187, 210],
        [210,  98, 208],
        [  9,  90, 200],
        [ 59, 207, 192],
        [142,  30, 159],
        [  2,  80, 228],
        [115, 241,  66],
        [253,  88, 125],
        [ 29, 165,  23],
        [236, 195, 

In [13]:
r

array([[169, 198, 150, 238,  92,  15,  56,  46, 200, 130],
       [129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,  27,  65, 103, 199, 119, 190],
       [163, 244, 151,  86,  92,  13,   4, 232, 234,  80],
       [ 74, 112, 116, 254, 233, 170, 144, 254, 174,  78],
       [132,   9, 224, 237, 186,  97,  43, 168, 155,  95],
       [194, 108, 205,  75,  57, 206, 190, 243,   8,  43],
       [ 52, 148,  22, 241,   7, 178,  16,  70, 148, 185],
       [140, 102, 185,  63,  25, 112,  33,  31, 166, 105],
       [ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0]], dtype=uint8)

In [14]:
r[0]

array([169, 198, 150, 238,  92,  15,  56,  46, 200, 130], dtype=uint8)

In [15]:
r[0,0]

169

In [16]:
r[1,0]

129

In [17]:
r[1:4]

array([[129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,  27,  65, 103, 199, 119, 190],
       [163, 244, 151,  86,  92,  13,   4, 232, 234,  80]], dtype=uint8)

In [18]:
r[1:4,0:3]

array([[129, 213, 144],
       [ 66,  69,  26],
       [163, 244, 151]], dtype=uint8)

In [26]:
r[5:-1,0]

array([132, 194,  52, 140], dtype=uint8)

In [27]:
r[0]

array([169, 198, 150, 238,  92,  15,  56,  46, 200, 130], dtype=uint8)

In [28]:
r[-1]

array([ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0], dtype=uint8)

In [31]:
r[-2]

array([140, 102, 185,  63,  25, 112,  33,  31, 166, 105], dtype=uint8)

In [32]:
r[-2]=255
r

array([[169, 198, 150, 238,  92,  15,  56,  46, 200, 130],
       [129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,  27,  65, 103, 199, 119, 190],
       [163, 244, 151,  86,  92,  13,   4, 232, 234,  80],
       [ 74, 112, 116, 254, 233, 170, 144, 254, 174,  78],
       [132,   9, 224, 237, 186,  97,  43, 168, 155,  95],
       [194, 108, 205,  75,  57, 206, 190, 243,   8,  43],
       [ 52, 148,  22, 241,   7, 178,  16,  70, 148, 185],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0]], dtype=uint8)

In [33]:
r[2:5,4:7]=0
r

array([[169, 198, 150, 238,  92,  15,  56,  46, 200, 130],
       [129, 213, 144, 195,  96, 254, 133, 130, 222, 189],
       [ 66,  69,  26, 212,   0,   0,   0, 199, 119, 190],
       [163, 244, 151,  86,   0,   0,   0, 232, 234,  80],
       [ 74, 112, 116, 254,   0,   0,   0, 254, 174,  78],
       [132,   9, 224, 237, 186,  97,  43, 168, 155,  95],
       [194, 108, 205,  75,  57, 206, 190, 243,   8,  43],
       [ 52, 148,  22, 241,   7, 178,  16,  70, 148, 185],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [ 74, 138, 168,  38, 204,  84, 222,  45,   0,   0]], dtype=uint8)

In [34]:
rgb

array([[[119,  79, 235],
        [134, 185,  52],
        [ 19, 222, 151],
        [ 38,  70,  85],
        [156, 117,  70],
        [126, 172, 163],
        [ 23, 225, 232],
        [188, 194,  41],
        [251, 137,  19],
        [232,  52, 222]],

       [[160,  22,   9],
        [114,  94, 118],
        [ 56, 234,  18],
        [128, 237,  10],
        [162,  77,  68],
        [186, 116,  62],
        [182, 146, 240],
        [ 96,  85,  21],
        [ 29, 159, 252],
        [167, 102,  97]],

       [[ 27, 234, 175],
        [ 90, 111, 130],
        [218,  84, 237],
        [116, 184, 232],
        [179, 148,  90],
        [110, 247,  77],
        [251, 213,  74],
        [ 62, 132, 147],
        [143, 107, 227],
        [ 44, 243, 114]],

       [[245, 187, 210],
        [210,  98, 208],
        [  9,  90, 200],
        [ 59, 207, 192],
        [142,  30, 159],
        [  2,  80, 228],
        [115, 241,  66],
        [253,  88, 125],
        [ 29, 165,  23],
        [236, 195, 

In [36]:
rgb[0:3,0:4]

array([[[119,  79, 235],
        [134, 185,  52],
        [ 19, 222, 151],
        [ 38,  70,  85]],

       [[160,  22,   9],
        [114,  94, 118],
        [ 56, 234,  18],
        [128, 237,  10]],

       [[ 27, 234, 175],
        [ 90, 111, 130],
        [218,  84, 237],
        [116, 184, 232]]])

In [37]:
rgb[0:3,0:4,1]

array([[ 79, 185, 222,  70],
       [ 22,  94, 234, 237],
       [234, 111,  84, 184]])

In [38]:
rgb[:,:,2]

array([[235,  52, 151,  85,  70, 163, 232,  41,  19, 222],
       [  9, 118,  18,  10,  68,  62, 240,  21, 252,  97],
       [175, 130, 237, 232,  90,  77,  74, 147, 227, 114],
       [210, 208, 200, 192, 159, 228,  66, 125,  23,  61],
       [  9,  95, 152, 149,  97, 254, 107,  94, 202, 121],
       [113,  13, 231, 214,  62,  73, 243,  79, 213,  56],
       [201, 239, 173, 230,  86, 198,  34, 184, 125,  44],
       [  3,  20, 236, 141,  27, 129, 139, 254, 109,  88],
       [165, 104,  25, 183, 108, 249, 199, 143, 133,  26],
       [107, 245, 254, 153, 114, 190,  33, 102, 101,  13]])

In [45]:
rgb[...,(0,2)]

array([[[119, 235],
        [134,  52],
        [ 19, 151],
        [ 38,  85],
        [156,  70],
        [126, 163],
        [ 23, 232],
        [188,  41],
        [251,  19],
        [232, 222]],

       [[160,   9],
        [114, 118],
        [ 56,  18],
        [128,  10],
        [162,  68],
        [186,  62],
        [182, 240],
        [ 96,  21],
        [ 29, 252],
        [167,  97]],

       [[ 27, 175],
        [ 90, 130],
        [218, 237],
        [116, 232],
        [179,  90],
        [110,  77],
        [251,  74],
        [ 62, 147],
        [143, 227],
        [ 44, 114]],

       [[245, 210],
        [210, 208],
        [  9, 200],
        [ 59, 192],
        [142, 159],
        [  2, 228],
        [115,  66],
        [253, 125],
        [ 29,  23],
        [236,  61]],

       [[185,   9],
        [ 23,  95],
        [ 49, 152],
        [167, 149],
        [239,  97],
        [104, 254],
        [237, 107],
        [ 14,  94],
        [253, 202],
        [241

In [46]:
r[6]=256

C:\Users\EMRE5\AppData\Local\Temp\ipykernel_20412\4009387356.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  r[6]=256


In [47]:
r2[6]=256